name: three_things_today
description: My journey to learn flutter.

dependencies:
  flutter:
    sdk: flutter
  sqflite: 1.1.6+5
  path_provider: ^1.3.0
  intl: ^0.15.7

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_admob: ^0.9.0+7

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/1.png
    - images/2.png
    - images/3.png
    - images/5.png
    - images/13.png
    - images/11.png




  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #  fonts:
  #    - family: Raleway
  #      fonts:
  #        - asset: fonts/Raleway-Regular.ttf
  #        - asset: fonts/Raleway-Bold.ttf
  #          weight: 700
  #        - asset: fonts/Raleway-LightItalic.ttf
  #          weight: 300
  #          style: italic
  #    - family: Roboto
  #      fonts:
  #        - asset: fonts/Roboto-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
